version: 2
jobs:
  build:
    docker:
      - image: markhobson/craftcms-aws-primary
    working_directory: ~/craftcms-aws
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build public assets
          command: |
            npm install
            npm run dist
      - run:
          name: Build Docker image
          command: docker build -t craftcms-aws .
      - run:
          name: Log Docker into AWS ECR
          command: $(aws ecr get-login --no-include-email)
      - run:
          name: Push Docker image to AWS ECR
          command: |
            docker tag craftcms-aws ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/craftcms-aws
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/craftcms-aws
      - run:
          name: Update AWS stack
          command: aws cloudformation update-stack --stack-name craftcms-aws --template-body file://template.yml --capabilities CAPABILITY_IAM
